server.port=8085
spring.application.name=payment-service

# ── Database (Derby) ──
spring.datasource.url=jdbc:derby:./data/paymentDB;create=true
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ── JWT ──
app.jwt.secret=dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RBdXRoMjU2Qml0cw==
app.jwt.expiration=86400000

# ── Razorpay ──
razorpay.key.id=rzp_test_SnYstMsDHKbFEd
razorpay.key.secret=Q1uRrKe7LLBtgiVOcnkjwsNI
razorpay.currency=INR
razorpay.company.name=Library Management System

# ── Swagger ──
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ── Eureka ──
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
